//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.25 at 09:07:47 PM EET 
//


package org.fpo.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for RURPayment element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="RURPayment">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="paymentDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *           &lt;element name="sum" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *           &lt;element name="fromCnum" type="{}cnum"/>
 *           &lt;element name="toCnum" type="{}cnum"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "paymentDate",
    "sum",
    "fromCnum",
    "toCnum"
})
@XmlRootElement(name = "RURPayment")
public class RURPaymentDto {

    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar paymentDate;
    protected long sum;
    @XmlElement(required = true)
    protected String fromCnum;
    @XmlElement(required = true)
    protected String toCnum;

    /**
     * Gets the value of the paymentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPaymentDate() {
        return paymentDate;
    }

    /**
     * Sets the value of the paymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPaymentDate(XMLGregorianCalendar value) {
        this.paymentDate = value;
    }

    /**
     * Gets the value of the sum property.
     * 
     */
    public long getSum() {
        return sum;
    }

    /**
     * Sets the value of the sum property.
     * 
     */
    public void setSum(long value) {
        this.sum = value;
    }

    /**
     * Gets the value of the fromCnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromCnum() {
        return fromCnum;
    }

    /**
     * Sets the value of the fromCnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromCnum(String value) {
        this.fromCnum = value;
    }

    /**
     * Gets the value of the toCnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToCnum() {
        return toCnum;
    }

    /**
     * Sets the value of the toCnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToCnum(String value) {
        this.toCnum = value;
    }

}
